
# слева русские, справа латинские
dict_symbols_navigator = {
    'А': 'A',
    'Б': 'a',
    'В': 'B',
    'Г': 'b',
    'Д': 'd',
    'Е': 'E',
    'Ё': 'e',
    'Ж': 'f',
    'З': 'g',
    'И': 'h',
    'Й': 'i',
    'К': 'K',
    'Л': 'j',
    'М': 'M',
    'Н': 'H',
    'О': 'O',
    'П': 'k',
    'Р': 'P',
    'С': 'C',
    'Т': 'T',
    'У': 'l',
    'Ф': 'm',
    'Х': 'X',
    'Ц': 'n',
    'Ч': 'o',
    'Ш': 'p',
    'Щ': 'q',
    'Ъ': 'r',
    'Ы': 's',
    'Ь': 't',
    'Э': 'u',
    'Ю': 'v',
    'Я': 'w',
}

dict_symbols_motorola = {
    'А': 'a',
    'Б': 'b',
    'В': 'w',
    'Г': 'g',
    'Д': 'd',
    'Е': 'e',
    'Ё': 'e',
    'Ж': 'v',
    'З': 'z',
    'И': 'i',
    'Й': 'j',
    'К': 'k',
    'Л': 'l',
    'М': 'm',
    'Н': 'n',
    'О': 'o',
    'П': 'p',
    'Р': 'r',
    'С': 's',
    'Т': 't',
    'У': 'u',
    'Ф': 'f',
    'Х': 'h',
    'Ц': 'c',
    'Ч': '~',
    'Ш': '{',
    'Щ': '}',
    'Ъ': 'x',
    'Ы': 'y',
    'Ь': 'x',
    'Э': '|',
    'Ю': '\'',
    'Я': 'q',
    'а': 'A',
    'б': 'B',
    'в': 'W',
    'г': 'G',
    'д': 'D',
    'е': 'E',
    'ё': 'E',
    'ж': 'V',
    'з': 'Z',
    'и': 'I',
    'й': 'J',
    'к': 'K',
    'л': 'L',
    'м': 'M',
    'н': 'N',
    'о': 'O',
    'п': 'P',
    'р': 'R',
    'с': 'S',
    'т': 'T',
    'у': 'U',
    'ф': 'F',
    'х': 'H',
    'ц': 'C',
    'ч': '^',
    'ш': '[',
    'щ': ']',
    'ъ': 'X',
    'ы': 'Y',
    'ь': 'X',
    'э': '\\',
    'ю': '@',
    'я': 'Q',
}


def encode_message(message_text, pager_type):
    result = ''
    if pager_type == 1:
        result = message_text.upper()
        for cyr_symbol, lat_symbol in dict_symbols_navigator.items():
            result = result.replace(cyr_symbol, lat_symbol)
    elif pager_type == 2:
        result = message_text
        for cyr_symbol, lat_symbol in dict_symbols_motorola.items():
            result = result.replace(cyr_symbol, lat_symbol)
    return result
