# Generated by Django 3.2.9 on 2021-11-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='fbit',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)]),
        ),
    ]
