# Generated by Django 3.2.9 on 2021-11-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_backend', '0002_alter_directmessage_fbit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='freq',
            field=models.CharField(max_length=9, verbose_name='Частота'),
        ),
    ]
