# Generated by Django 3.2.9 on 2021-11-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_backend', '0003_alter_directmessage_freq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='capcode',
            field=models.CharField(max_length=7, verbose_name='Капкод'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='fbit',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], verbose_name='Бит источника'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='freq',
            field=models.CharField(max_length=9, verbose_name='Частота (Гц)'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='message',
            field=models.TextField(max_length=1500, verbose_name='Сообщение'),
        ),
    ]
