# Generated by Django 3.2.9 on 2021-11-22 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_backend', '0004_auto_20211111_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='capcode',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9999999)], verbose_name='Капкод'),
        ),
    ]
