# Generated by Django 3.2.9 on 2021-11-23 03:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_backend', '0005_alter_directmessage_capcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='capcode',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999)], verbose_name='Капкод'),
        ),
    ]
