# Generated by Django 3.2.9 on 2021-11-23 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_backend', '0006_alter_directmessage_capcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='freq',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(60000000), django.core.validators.MaxValueValidator(999999999)], verbose_name='Частота (Гц)'),
        ),
    ]
