# Generated by Django 3.2.9 on 2021-11-23 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_backend', '0007_alter_directmessage_freq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transmitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(60000000), django.core.validators.MaxValueValidator(999999999)], verbose_name='Частота (Гц)')),
            ],
        ),
    ]
