# Generated by Django 3.2.9 on 2021-11-23 09:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_backend', '0008_transmitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abon_number', models.PositiveIntegerField(unique=True, verbose_name='Абонентский номер')),
                ('capcode', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999)], verbose_name='Приватный капкод')),
                ('fbit', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], verbose_name='Бит источника')),
                ('codepage', models.PositiveSmallIntegerField(choices=[(1, 'lat'), (2, 'cyr'), (3, 'linguist')], verbose_name='Тип кодировки')),
                ('id_transmitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_backend.transmitter')),
            ],
        ),
    ]
