# Generated by Django 3.2.9 on 2021-11-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_backend', '0010_auto_20211123_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pager',
            old_name='id_transmitter',
            new_name='transmitter',
        ),
    ]
