# Generated by Django 3.2.9 on 2021-11-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_backend', '0011_rename_id_transmitter_pager_transmitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО клиента')),
                ('pagers', models.ManyToManyField(to='rest_backend.Pager', verbose_name='Пейджеры клиента')),
            ],
        ),
    ]
