# Generated by Django 3.2.9 on 2021-11-24 05:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_backend', '0012_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pager',
            old_name='abon_number',
            new_name='subscriber_number',
        ),
        migrations.AddField(
            model_name='client',
            name='datar',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='pager',
            name='transmitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_backend.transmitter', verbose_name='Трансмиттер'),
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1500, verbose_name='Сообщение')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_backend.client', verbose_name='Получатель')),
            ],
        ),
    ]
