# Generated by Django 3.2.9 on 2021-12-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_backend', '0013_auto_20211124_1207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateMessage',
        ),
    ]
