# Generated by Django 3.2.9 on 2021-12-02 07:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_backend', '0014_delete_privatemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1500, verbose_name='Сообщение')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('pager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_backend.pager', verbose_name='Пейджер-получатель')),
            ],
        ),
    ]
