# Generated by Django 3.2.9 on 2021-12-03 14:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_backend', '0015_privatemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'экстренное'), (2, 'новости'), (3, 'погода'), (4, 'курсы валют'), (5, 'юмор'), (6, 'гороскоп'), (7, 'нет'), (8, 'нет')], verbose_name='Тип рассылки')),
                ('capcode', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999)], verbose_name='Новостной капкод')),
                ('fbit', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], verbose_name='Бит источника')),
                ('codepage', models.PositiveSmallIntegerField(choices=[(1, 'lat'), (2, 'cyr'), (3, 'linguist')], verbose_name='Тип кодировки')),
                ('transmitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_backend.transmitter', verbose_name='Трансмиттер')),
            ],
        ),
        migrations.CreateModel(
            name='NewsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1500, verbose_name='Новостное сообщение')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_backend.newschannel', verbose_name='Новостной канал')),
            ],
        ),
    ]
