# Generated by Django 3.2.9 on 2021-12-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_backend', '0017_directmessage_codepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmessage',
            name='channel',
        ),
        migrations.AddField(
            model_name='newsmessage',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'экстренное'), (2, 'новости'), (3, 'погода'), (4, 'курсы валют'), (5, 'юмор'), (6, 'гороскоп'), (7, 'нет'), (8, 'нет')], default=0, verbose_name='Тип рассылки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsmessage',
            name='message',
            field=models.TextField(max_length=1500, verbose_name='Текст новостного сообщения'),
        ),
    ]
