# Generated by Django 3.2.10 on 2021-12-17 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_backend', '0018_auto_20211206_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='capcode',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)], verbose_name='Капкод'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='fbit',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], verbose_name='Биты источника'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='message',
            field=models.TextField(max_length=950, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='newsmessage',
            name='message',
            field=models.TextField(max_length=950, verbose_name='Текст новостного сообщения'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='message',
            field=models.TextField(max_length=950, verbose_name='Сообщение'),
        ),
    ]
