# Generated by Django 3.2.10 on 2021-12-19 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_backend', '0019_auto_20211217_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='codepage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'lat'), (2, 'cyr'), (3, 'linguist')], verbose_name='Кодировка текста'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='fbit',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='newschannel',
            name='capcode',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)], verbose_name='Новостной капкод'),
        ),
        migrations.AlterField(
            model_name='newschannel',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'экстренное'), (2, 'уведомления'), (3, 'новости'), (4, 'погода'), (5, 'курсы валют'), (6, 'юмор'), (7, 'гороскоп'), (8, 'резерв')], verbose_name='Тип рассылки'),
        ),
        migrations.AlterField(
            model_name='newschannel',
            name='codepage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'lat'), (2, 'cyr'), (3, 'linguist')], verbose_name='Кодировка текста'),
        ),
        migrations.AlterField(
            model_name='newschannel',
            name='fbit',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='newsmessage',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'экстренное'), (2, 'уведомления'), (3, 'новости'), (4, 'погода'), (5, 'курсы валют'), (6, 'юмор'), (7, 'гороскоп'), (8, 'резерв')], verbose_name='Тип рассылки'),
        ),
        migrations.AlterField(
            model_name='newsmessage',
            name='message',
            field=models.TextField(max_length=950, verbose_name='Новостное сообщение'),
        ),
        migrations.AlterField(
            model_name='pager',
            name='capcode',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)], verbose_name='Приватный капкод'),
        ),
        migrations.AlterField(
            model_name='pager',
            name='codepage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'lat'), (2, 'cyr'), (3, 'linguist')], verbose_name='Кодировка текста'),
        ),
        migrations.AlterField(
            model_name='pager',
            name='fbit',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='transmitter',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
